$ ->
  grid = $('#grid').kendoGrid(
    dataSource:
      type: 'json'
      transport:
        read: url: '/Phones'
        create:
          url: '/Phones'
          type: 'POST'
    serverPaging: false
    sortable:
      mode: 'single'
      allowUnsort: false
    pageable:
      pageSize: 5
      buttonCount: 1
      numeric: false
      info: true
    detailTemplate: kendo.template($('#template').html())
    detailInit: detailInit
    mobile: true
    dataBound: ->
      #If stock is "out of stock", color the text 'red'
      $('td').each ->
        if $(this).text() == 'Out of stock'
          $(this).addClass 'outofstock'
        return
      # Make table more easily readable using odd & even rules
      $('tr:odd').css 'background-color', '#e9e9e9'
      return
    columns: [
      {
        field: 'Model'
        title: 'Model'
        width: '260px'
      }
      {
        field: 'Display'
        title: 'Display'
        width: '160px'
      }
      {
        field: 'OS'
        width: '160px'
      }
      {
        field: 'Stock'
        width: '160px'
      }
      {
        field: 'Monthly'
        width: '160px'
      }
      {
        field: 'Onetime'
        width: '160px'
      }
    ])
  validator = $('#phoneForm').kendoValidator().data('kendoValidator')
  status = $('.status')
  #Adds details some fade effect

  detailInit = (e) ->
    detailRow = e.detailRow
    detailRow.find('.tabstrip').kendoTabStrip animation: open: effects: 'fadeIn'
    return

  $('form').submit (event) ->
    if validator.validate()
      status.text('Phone added!').removeClass('invalid').addClass 'valid'
    else
      status.text('Oops! There is invalid data in the form.').removeClass('valid').addClass 'invalid'
    return
  timeout = undefined
  $('#search').find('#searchBox').keydown ->
    # Keydown makes filter live action so no need to press any buttons
    # Clears any pending filtering requests 
    clearTimeout timeout
    searchValue = $('#searchBox').val()
    # Filters the grid after 100 milliseconds
    timeout = setTimeout((->
      grid.data('kendoGrid').dataSource.filter
        logic: 'or'
        filters: [
          {
            field: 'Model'
            operator: 'contains'
            value: searchValue
          }
          {
            field: 'Display'
            operator: 'contains'
            value: searchValue
          }
          {
            field: 'OS'
            operator: 'contains'
            value: searchValue
          }
        ]
      return
    ), 100)
    return
  # Adds some resizing for mobile screens
  $(window).on 'resize', ->
    kendo.resize $('.wrapper')
    return
  $('#addNew').hide()
  $('#addNew-btn').click ->
    $('#addNew').toggle 'slow'
    return
  return

# ---
# generated by js2coffee 2.2.0